spring.application.name=SeaPackBackEnd
server.address=0.0.0.0
server.port=8090
##?????
spring.datasource.url=jdbc:mysql://localhost:3306/sea_pack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=seapack
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring.datasource.druid.initial-size=5
spring.datasource.druid.min-idle=5
spring.datasource.druid.max-active=20
##mybatis??
# XML??????
mybatis.mapper-locations=classpath:mapper/**/*.xml
# ??????
mybatis.type-aliases-package=org.seapack.model
# ??????
mybatis.configuration.map-underscore-to-camel-case=true
# ??SQL????????
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# pageHelper Setting
pagehelper.helper-dialect=mysql
pagehelper.reasonable=true
pagehelper.support-methods-arguments=true
pagehelper.params=count=countSql
pagehelper.page-size-zero=true

#redis-setting
# public-IP??
spring.data.redis.host=113.44.41.182
spring.data.redis.port=6379
# ??????
spring.data.redis.password=seapack

#langchain4j setting
deepseek.api-key=sk-xxxxxxxxxxxxxxxxxxxxxxxx
deepseek.base-url=https://api.deepseek.com
deepseek.model=deepseek-chat
deepseek.embedding-model=text-embedding-3-small

#rsa
rsa.private-key=MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCyl8fmX36ye+Hhd3QQ8ju99gz8hrvpp8CAMawpYJYQhJbf90aB88jBagO2toYBL7/Ox2FGgAuiXvoOHxNnMAurN9uiMkT6dTKM8Y51FytQwbR0KgM7VhQLprjEIcn/n2TmGyDda0y0Y8g/x5hR1iYTkbPyQ52xS98kEPWxH5lnnAWMhQ1Llm05tcvzP7lLDURxznybBSiE4AhLk6Dq2dvlB34wil/uxiMURgD7pUfXvCnW51MIQWWrc6vzF3WE4znjVjTf4b0Z+WgJ80o/qIew3iGqPHI+R8Sk57+O1OCTow/hmDkiqf0kfdnkGx2qPqrXwTeJpTU0oFSE+aOyVlbjAgMBAAECggEAFQ3LpR7w4r2z/U6FwlGsNVLCaSrBEGSUTwiMETyvtDbNSo3uI/fHXPXQhkOyPIWSiR/8GcGSnYuw0uVa9jk1xvOI0vA2LYiPcwovDyKyGo0bZu5k/yPArTb0ZTrOg3IZBP+Bulih7EovG0W+cTdbucbdfdv2xSX6olfVfxIIlaweSDVk8oJSSMiRnTpydIxBSZDLUan0s+GciA3bIxzvtLD4Dp6kCpUu2IGFms9esjrnwgCIRj7rSgepVvm0Wd/ZbuSPyndM60Kw8lXNV66Qq6+iw5HnhoA3c89O+nkWr+uO2/ISn8IC75DBdSRuGcniYfgIED/HMSmEcW5Koe2WgQKBgQC/LCaqxk+s+DLcYd68XjIunPItIjIU805lNFHr7XoIRfWxfTdlyJ/GOnKhoWgLs0eR47rzF8cpNFDWOS4aJvlfFj2wYjmTWnQq5g8q2OyHZHPJQW9oGwhj5ig9Gpi2b9WQL37gSRB2Ho6RN3UEJB1y6Hq0YRAwC1sj4n/juHt4wwKBgQDvJ5YUU1VN1nUjdryEWPwG3Ee0Ub/YmA2MPSZuP3Fcahj/iwJOEn5SUwVWEFDu84/DuWBjKSoyoEIRnOrFWJrzS961KkDecnYwUO4B7amh/QOcwoINXxkCYEnazIEL9CWLpATZ0QelDrFJq/1m63TpV/fIZq6eaXZPFltlcbrHYQKBgC/Tz+ixrIVNowvXwG3H8y4OPdhk0brEFDzllgk8ZGdleU5qUU25n59sR/l/9BPZSnKJUuA2drEsUX0G2S3ZylGrsstKB7WBz8ZbwDesBaDp1L3pDQIyoSq9DhwbZ1FdMUTdXRSnsuKaSniyMyhSELwKxYgTMIWUkbyskepa4SkZAoGBAJtXQkO3kVw65eGAOZlZ13J5WNYGl6+PrJUgDztjWDXn8I7kcz3VA1pj9L5fYMKlUAeY/MPMNE2oDOI148UF9bf82w8f//y9qolduAtmnV3L47HKIgGfeLYzZyWI2nWyQ0T95+y3uth6v6uT3MgiPtFmw1rXX6sj46YhZoJxKhphAoGBAJCFnmWMIDbwJm7R+KYKUTemFGPoRiUYzr6U+3gcbiswNBigDECyD+vdOc720YgjcFS5gFWNxIoxz8tIqdMvch6qKAyUbcKONLSXcl4ODuLkHQ2Yk6Mto0gjc3kS7rQGDI2tRC1U8xCqGEuu0L322/bsMdfIpfcgDhS3jblbQyrU
rsa.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAspfH5l9+snvh4Xd0EPI7vfYM/Ia76afAgDGsKWCWEISW3/dGgfPIwWoDtraGAS+/zsdhRoALol76Dh8TZzALqzfbojJE+nUyjPGOdRcrUMG0dCoDO1YUC6a4xCHJ/59k5hsg3WtMtGPIP8eYUdYmE5Gz8kOdsUvfJBD1sR+ZZ5wFjIUNS5ZtObXL8z+5Sw1Ecc58mwUohOAIS5Og6tnb5Qd+MIpf7sYjFEYA+6VH17wp1udTCEFlq3Or8xd1hOM541Y03+G9GfloCfNKP6iHsN4hqjxyPkfEpOe/jtTgk6MP4Zg5Iqn9JH3Z5Bsdqj6q18E3iaU1NKBUhPmjslZW4wIDAQAB

logging.level.org.springframework.data.redis=DEBUG