CREATE TABLE `ai_execution_session` (
  `id`                  BIGINT        NOT NULL AUTO_INCREMENT  COMMENT '主键',
  `biz_type`            VARCHAR(30)   NOT NULL                 COMMENT '调用类型：agent/orchestration/chat/prompt/knowledge',
  `biz_id`              BIGINT        NOT NULL DEFAULT 0       COMMENT '关联实体ID（Agent ID / 编排ID / 提示词模板ID，通用对话为0）',
  `biz_name`            VARCHAR(100)  DEFAULT NULL             COMMENT '关联实体名称（冗余，方便展示）',
  `conversation_id`     VARCHAR(64)   DEFAULT NULL             COMMENT '对话ID，同一会话的所有轮次共享，由前端生成',
  `scene_id`            BIGINT        DEFAULT NULL             COMMENT '场景ID，关联 ai_scene 表',
  `request_id`          VARCHAR(64)   DEFAULT NULL             COMMENT '消息ID，每条消息唯一，由前端生成，用于精确定位某一轮对话',
  `retry_count`         TINYINT UNSIGNED DEFAULT 0             COMMENT '重试次数',
  `user_message`        TEXT          DEFAULT NULL             COMMENT '当轮用户输入',
  `history_messages`    JSON          DEFAULT NULL             COMMENT '对话历史（JSON数组，可选存储）',
  `output_result`       TEXT          DEFAULT NULL             COMMENT '当轮AI输出',
  `trace_snapshot`      JSON          DEFAULT NULL             COMMENT '完整调用链路快照（编排步骤/Agent详情/LLM信息）',
  `total_duration_ms`   INT           DEFAULT NULL             COMMENT '总耗时（毫秒）',
  `tokens_prompt`       INT           DEFAULT NULL             COMMENT '提示词Token数',
  `tokens_completion`   INT           DEFAULT NULL             COMMENT '补全Token数',
  `tokens_total`        INT           DEFAULT NULL             COMMENT '总Token数',
  `model_name`          VARCHAR(100)  DEFAULT NULL             COMMENT '使用的模型',
  `status`              VARCHAR(20)   DEFAULT 'success'        COMMENT '状态：success/fail/timeout/cancelled',
  `is_deleted`          TINYINT UNSIGNED DEFAULT 0             COMMENT '逻辑删除：0-未删除，1-已删除',
  `error_message`       TEXT          DEFAULT NULL             COMMENT '错误信息',
  `created_by`          BIGINT        DEFAULT NULL             COMMENT '操作人（用户ID）',
  `created_at`          DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_request_id` (`request_id`),
  KEY `idx_conversation` (`conversation_id`),
  KEY `idx_scene_user` (`scene_id`, `created_by`),
  KEY `idx_biz` (`biz_type`, `biz_id`),
  KEY `idx_created_by` (`created_by`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI 执行会话记录表（一轮对话一条记录）';